/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_xah_bsdiff_logic_util_BsdiffJNI */

#ifndef _Included_org_xah_bsdiff_logic_util_BsdiffJNI
#define _Included_org_xah_bsdiff_logic_util_BsdiffJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xah_bsdiff_logic_util_BsdiffJNI
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT int JNICALL Java_org_xah_bsdiff_logic_util_BsdiffJNI_patch
  (JNIEnv *, jobject, jstring, jstring, jstring);

JNIEXPORT int JNICALL Java_org_xah_bsdiff_logic_util_BsdiffJNI_merge
  (JNIEnv *env, jobject obj, jstring oldFilePath, jstring patchFilePath, jstring newFilePath);

JNIEXPORT jstring JNICALL Java_org_xah_bsdiff_logic_util_PickFile_pickFile
  (JNIEnv * env, jobject obj);


#ifdef __cplusplus
}
#endif
#endif
